# Generated by Django 3.2.15 on 2022-09-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uptime',
            old_name='response',
            new_name='responsible',
        ),
    ]
