# Generated by Django 3.2.15 on 2022-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0002_rename_response_uptime_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uptimeinstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancename', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
