# Generated by Django 3.2.15 on 2022-09-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0003_uptimeinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uptimeinstance',
        ),
    ]
